name: odk_basis_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  webview_flutter: ^2.0.13
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  path: ^1.8.0
  flutter_secure_storage: ^9.2.2
  xml: ^5.3.1
  csv: ^5.0.1
  excel: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
